name = "MyPackage"
uuid = "0b48ad8b-a282-4514-80d9-bf0add6b76ed"

[deps]
ParallelTestRunner = "d3525ed8-44d0-4b2c-a655-542cee43accc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources]
ParallelTestRunner = {path = ".."}

[compat]
julia = "1.10"
